In [7]:
 import numpy as np 

In [ ]:
#array generating functions
#use shift + tab functions over a function to get its info

In [22]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [27]:
arr = np.arange(1, 10, 2) #start, end, steps
arr

array([1, 3, 5, 7, 9])

In [28]:
arr = np.zeros(6) #zero vector 
arr

array([0., 0., 0., 0., 0., 0.])

In [29]:
arr = np.zeros((4, 6)) #(rows, cols)
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [37]:
arr = np.linspace(1, 5, 12) #return evenly spaced numbres over a fixed interval (start, range, number of elements)
arr

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [ ]:
#random generating functions

In [38]:
arr = np.random.rand(5) #creates n random number in between 0 and 1 
arr

array([0.28491521, 0.31564878, 0.98369498, 0.11450194, 0.22470149])

In [44]:
arr = np.random.randn(5) #randn : created no between -3 to 3
arr

array([ 1.02535857, -0.25395201, -0.76001692, -0.19960153, -1.59823658])

In [45]:
np.random.randint(6) #creates a number no between 0 and m

1

In [48]:
np.random.randint(2, 10, 30)  #(start, end, count)

array([9, 5, 7, 5, 8, 7, 3, 8, 5, 5, 5, 8, 7, 7, 6, 7, 5, 6, 8, 7, 9, 3,
       5, 6, 6, 3, 5, 3, 4, 5], dtype=int32)

In [ ]:
#ARRAY ATTRIBUTES

In [51]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [52]:
arr.shape #shape of array row x cols

(3, 3)

In [53]:
arr.size #no of elements

9

In [54]:
arr.dtype #data type

dtype('int64')

In [ ]:
#array methods: need to call 

In [78]:
arr = np.array([[1, 8, 8, 10], [1, 18, 8, -1]])

In [70]:
arr.min()

np.int64(-1)

In [71]:
arr.max()

np.int64(10)

In [72]:
arr.sum() #sum of alll elements of array

np.int64(43)

In [ ]:
#row wise and col wise sum:-

In [73]:
np.sum(arr, axis=0) #axis0 sum of same col elements

array([ 2, 16, 16,  9])

In [74]:
np.sum(arr, axis=1) #axis = 1 sum of same row elements

array([27, 16])

In [75]:
arr.mean()

np.float64(5.375)

In [76]:
arr.std() #standard deviation

np.float64(3.998046397929869)

In [79]:
arr.argmax() #index of maximum element

np.int64(5)

In [80]:
arr.argmin() #index of minimum element

np.int64(7)

In [ ]:
#reshaping and resizing

In [81]:
arr = np.arange(1, 31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [84]:
arr.reshape(6, 5) #reshape an array in n rows m cols

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
#indexing and slicing in arrays

In [94]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [95]:
arr[0] #same indexing as of list

np.int64(11)

In [98]:
arr[0: 2] #arr slicing startPoint(inclusive) : endPoint(exclusive)

array([11, 12])

In [99]:
arr[:5] #default value set to 0

array([11, 12, 13, 14, 15])

In [100]:
arr[1:] #till end of array

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [101]:
arr[0:4:2] #start : end : steps

array([11, 13])

In [103]:
#numpy indexing and slicing of 2d matrix
arr = np.arange(1, 31).reshape(6, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [107]:
arr[0] #target entire row

np.int64(1)

In [110]:
arr[0, 0] #row,col

np.int64(30)

In [112]:
arr[5, 4] #row,col

np.int64(30)

In [113]:
arr[0:2, 1:3] #rowa - rowb(exlusive), cola - colb(exclusive)

array([[2, 3],
       [7, 8]])

In [116]:
arr[3:, 3:] #row 3 to end , col 3 to end

array([[19, 20],
       [24, 25],
       [29, 30]])

In [120]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [121]:
#boolean indexing
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [123]:
even_indxArray = (arr % 2 == 0) #true on even elements
even_indxArray

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [124]:
newarr = arr[even_indxArray] #select all elements with true value of even_indxArray
newarr

array([12, 14, 16, 18, 20])

In [ ]:
#Array operations

In [131]:
#arithmetic operations
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([6, 7, 8, 9, 10])

In [132]:
a1 + a2 # no of rows and cols must be same

array([ 7,  9, 11, 13, 15])

In [133]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [134]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [135]:
a1 // a2

array([0, 0, 0, 0, 0])

In [136]:
a1 ** a2 

array([      1,     128,    6561,  262144, 9765625])

In [137]:
a1 + 10 #increments all no by 10

array([11, 12, 13, 14, 15])

In [138]:
a1 - 10 #decrements all no by 10

array([-9, -8, -7, -6, -5])

In [141]:
a1 = np.arange(1, 31).reshape(6, 5)
a1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [146]:
a2 = np.arange(1, 31).reshape(6, 5)
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [144]:
a1 + a2 #2d matrix array manipulation

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50],
       [52, 54, 56, 58, 60]])

In [148]:
a = np.arange(1, 21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [153]:
slice_a = a[:5]
slice_a = slice_a * 10 #results not reflected in original array
slice_a 

array([10, 20, 30, 40, 50])

In [154]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [155]:
b = a;
b[0] = 10;
a #this changes value a and b points to same memory reference

array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
# MATRIX OPERATIONS

In [159]:
a = np.arange(1, 5).reshape(2, 2);
a

array([[1, 2],
       [3, 4]])

In [163]:
b = np.arange(5, 9).reshape(2, 2);
b

array([[5, 6],
       [7, 8]])

In [162]:
a * b #multiply same row and col

array([[ 5, 12],
       [21, 32]])

In [164]:
a @ b #real matrix multiplication

array([[19, 22],
       [43, 50]])

In [165]:
np.dot(a, b)#method 2 for real matrix multiplications

array([[19, 22],
       [43, 50]])

In [166]:
a.transpose() #transpose

array([[1, 3],
       [2, 4]])

In [ ]:
#Advance array manipulation: stacking and splitting

In [169]:
#stacking: horizontal stacking, vertical stacking, normal stacking: creates a new dimension
np.hstack((a, b)) #append b in right of a 

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [170]:
np.vstack((a, b)) #append b in bottom of a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [171]:
np.stack((a, b)) #creates a new dimension

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [172]:
a = np.arange(16).reshape(4, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [176]:
#Splitting of array: Two types horizontal and vertical
np.hsplit(a, 4) #divide array in 4 parts horizontally

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [179]:
res = np.vsplit(a, 4) #divide array in 4 parts vertically

In [180]:
for i in res:
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
